name: 'Build Rebol for Apple M1'
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Siskin Builder
        uses: oldes/install-siskin@v0.4.1

      - name: List some directories
        run: |
          ls -la /Library/Developer/CommandLineTools/SDKs/
          ls -la /Applications/

      - name: Setup MacOSX SDK
        run: |
          curl -L -S https://github.com/Siskin-framework/MacOSX-SDK/releases/download/11.3/MacOSX.sdk.zip --output MacOSX.sdk.zip
          unzip -q MacOSX.sdk.zip
          export SDKROOT="$PWD/MacOSX.sdk"
          echo $SDKROOT
#          export SDKROOT=/Applications/Xcode_12.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk

      - name: Build 64bit Rebol/Bulk using clang
        run: export SDKROOT="$PWD/MacOSX.sdk" & ./siskin make/rebol3.nest %rebol3-bulk-arm64-osx

      - name: Prepare 64bit Rebol/Bulk for upload
        run: |
          echo $SDKROOT
          mv ./build/rebol3-bulk-arm64-osx ./rebol3-bulk-arm64-osx
          file ./rebol3-bulk-arm64-osx
          gzip -9 ./rebol3-bulk-arm64-osx

      - uses: actions/upload-artifact@v2
        with:
          name: Rebol-arm64-osx-${{github.run_id}}
          path: ./*.gz